apiVersion: v1
kind: Secret
metadata:
  name: kafka-cluster-credentials
stringData:
  CONNECT_BOOTSTRAP_SERVERS: "<enter confluent cloud bootstrap server>"
  CONNECT_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required username='<enter confluent cloud API Key>' password='<enter confluent cloud Secret>';
  CONNECT_PRODUCER_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required username='<enter confluent cloud API Key>' password='<enter confluent cloud Secret>';
  CONNECT_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required username='<enter confluent cloud API Key>' password='<enter confluent cloud Secret>';
  CONNECT_CONSUMER_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required username='<enter confluent cloud API Key>' password='<enter confluent cloud Secret>';
  CONNECT_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required username='<enter confluent cloud API Key>' password='<enter confluent cloud Secret>';
